---
micronaut:
    application:
        name: micronaut-cassandra-tc-ms
    server:
        port: 8086

---
cassandra:
    default:
        clusterName: "stores_ny_keyspace"
        contactPoint: "localhost"
        port: 9042
        maxSchemaAgreementWaitSeconds: 70
        ssl: false